<a href="https://colab.research.google.com/github/umeshbagade/M-L/blob/main/numpy_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)
print(arr[1:4])
print(numpy.__version__)
print(type(arr))

[1 2 3 4 5]
[2 3 4]
1.19.5
<class 'numpy.ndarray'>


In [42]:
import numpy as np
arr = np.array(23)  #0 dimentional array
arr1dim = np.array([1,23,4])
print(arr,arr1dim)


# 2 dimentional array
dim = np.array([[1,2],[1,2]])
print(f"printing 2 dimentional array : {dim} and bro this is f string ")


# dealing with 3 dimentional arrays 
dim3  = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(f" now printing 3 dimentional array\n:{dim3}")

#printing dimentions
print(arr.ndim)
print(dim.ndim)
print(dim3.ndim)



dim5arr = np.array([1,2,3,4,5],ndmin=5)
print(dim5arr)
print(f'number of dimentions in array {dim5arr.ndim}')
print(dim5arr[0][0][0][0][2])

23 [ 1 23  4]
printing 2 dimentional array : [[1 2]
 [1 2]] and bro this is f string 
 now printing 3 dimentional array
:[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
0
2
3
[[[[[1 2 3 4 5]]]]]
number of dimentions in array 5
3


In [70]:
#Arithmetic
x = np.array([[1,2],[3,4]])
y = np.array([[1,2],[3,4]])
print(f"X + Y =\n{np.add(x,y)}")

print(f"X - Y =\n{np.subtract(x,y)}")

print(f"X * Y =\n{np.multiply(x,y)}")

print(f"X . Y =\n{np.dot(x,y)}")

X + Y =
[[2 4]
 [6 8]]
X - Y =
[[0 0]
 [0 0]]
X * Y =
[[ 1  4]
 [ 9 16]]
X . Y =
[[ 7 10]
 [15 22]]


In [81]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8],[9,10],[11,12]])
c = np.dot(a,b) # giving similar value as c= a.dot(b)
print("X . Y = \n",a.dot(b))

#now printing shape
print(f"{a.shape} . {b.shape} = {c.shape}")

X . Y = 
 [[ 58  64]
 [139 154]]
(2, 3) . (3, 2) = (2, 2)


In [86]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))
print(np.sum(x,axis=0)) #row addition
print(np.sum(x,axis=1)) #column addition

10
[4 6]
[3 7]
